# Generated by Django 3.1.7 on 2021-03-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KampaniaRedlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kampanii', models.CharField(max_length=100)),
                ('kiedy_wyslany', models.CharField(max_length=100)),
                ('temat_mailingu_pl', models.CharField(max_length=100)),
                ('temat_mailingu_en', models.CharField(max_length=100)),
                ('temat_mailingu_de', models.CharField(max_length=100)),
                ('temat_mailingu_fr', models.CharField(max_length=100)),
                ('link_content', models.CharField(max_length=200)),
                ('ctr_pl', models.FloatField(default=0)),
                ('open_rate_pl', models.FloatField(default=0)),
                ('ctr_en', models.FloatField(default=0)),
                ('open_rate_en', models.FloatField(default=0)),
                ('ctr_de', models.FloatField(default=0)),
                ('open_rate_de', models.FloatField(default=0)),
                ('ctr_fr', models.FloatField(default=0)),
                ('open_rate_fr', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Handlowiec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redlink_id', models.CharField(max_length=100)),
                ('jezyk', models.CharField(max_length=100)),
                ('ctr', models.FloatField(default=0)),
                ('open_rate', models.FloatField(default=0)),
                ('dostarczone_wiadomosci', models.IntegerField(default=0)),
                ('un_sub', models.IntegerField(default=0)),
                ('kampania_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendmailing.kampaniaredlink')),
            ],
        ),
    ]
