# Generated by Django 3.1.7 on 2021-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampaniaredlink',
            name='dostarczone_wiadomoscidostarczone_wiadomosci_de',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='dostarczone_wiadomoscidostarczone_wiadomosci_en',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='dostarczone_wiadomoscidostarczone_wiadomosci_fr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='dostarczone_wiadomoscidostarczone_wiadomosci_pl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='un_sub_de',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='un_sub_en',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='un_sub_fr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='un_sub_pl',
            field=models.IntegerField(default=0),
        ),
    ]
