# Generated by Django 3.1.7 on 2021-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmailing', '0003_handlowiec_imie_nazwisko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlowiec',
            name='kampania_id',
        ),
        migrations.AddField(
            model_name='handlowiec',
            name='nazwa_kampanii',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
