# Generated by Django 3.1.7 on 2021-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmailing', '0005_auto_20210308_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlowiec',
            name='hard_bounces',
            field=models.IntegerField(default=0),
        ),
    ]
