# Generated by Django 3.1.7 on 2021-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmailing', '0006_handlowiec_hard_bounces'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampaniaredlink',
            name='hard_bounces_de',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='hard_bounces_en',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='hard_bounces_fr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampaniaredlink',
            name='hard_bounces_pl',
            field=models.IntegerField(default=0),
        ),
    ]
